<!DOCTYPE html>
<html>
    <head>
        <?php include './includes/metas.php'; ?>

    </head>
    <body>

        <?php include './includes/menu.php'; ?>

        <div class="container-fluid">

            <div class="faleconosco titulo-principal">
                <div class="row no-padding">
                    <div class="col-lg-offset-1 col-lg-5 col-md-offset-1 col-md-5 col-sm-12 col-xs-12 titulo">
                        <h1>
                            FALE CONOSCO
                        </h1>

                        <div class="col-md-offset-3 col-md-9">
                            <strong class="text-uppercase">roltex texturização e polimento</strong>
                            <a href="mailto:roltex@roltex.com.br">
                                roltex@roltex.com.br
                            </a>
                            <a href="tel:555432116170">
                                055 (54) 3211-6170
                            </a>
                            <span>
                                R. Antônio Rossato, 184-A 
                                B. Marechal Floriano <br/>
                            </span>
                            <span>
                                Caxias do Sul - RS Brasil
                            </span>
                        </div>
                    </div>

                    <!--                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 map-responsive" id="mapa">
                                            
                                        </div>-->
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 map-responsive no-padding-right">
                        <img src="http://weecom.com.br/projetos/roltex/7.html" usemap="#image-map">

                        <map name="image-map">
                            <area target="" alt="" title="" href="" coords="" shape="rect">
                        </map>
                        <svg width="0" height="0">
                        <clipPath >
                            <!--<polygon points="235,0 465,0 455,500 0,470" >-->
                            <polyline points="60 110, 65 120, 70 115, 75 130, 80 125, 85 140, 90 135, 95 150, 100 145"/>
                            </polygon>
                        </clipPath>
                        <defs>
                        </svg>
                    </div>
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                </div>
            </div>
            <?php include './includes/footer.php'; ?>
            <!-- /.container -->
        </div>
    </body>
    <script type="text/javascript" src="jquery.svg.js"></script>
</html>
